### ISSUE TITLE
2번째 피드백 및 과제

### ISSUE THREAD

**Issue by hyemdooly** [SullivanEducation/Arduino-RC-Car#3]
지금 문서에서는 피드백 할 사항이 없는 것 같아요. 경험이 있으셔서 그런지 잘하시는 것 같습니다!
대신 과제를 드리고 싶어요. :)

1. 기존에 있던 조이스틱 만들기 교육, 또는 비슷한 컨샙의 교육은 어느것이 있는지 찾아보고, 똑같거나 가장 비슷한거 하나 고르기
- 지금 1,2차시 참고에 적어두신 것 처럼 유튜브도 좋고요,
- 한차시 또는 단발성 유료교육,
- 학원 커리큘럼도 좋습니다.
2. 똑같거나 가장 비슷하다고 생각한 교육은 어떤게 문제일지?
3. 그것과 여러분이 만드는 교육과 비교했을때, 우리는 어떤부분이 더 좋고, 어떤부분이 더 안좋은지?

동우님이 조이스틱팀에게 피드백하면서 같이 제시한 과제인데, RC카팀 분들도 한번 생각해보면 좋을 것 같아요.
우선은 1번에 대한 것만 생각해보시고, 이슈 코멘트로 닫아주세요!
1차시(가능하다면 2차시까지) 기획서를 9월 14일까지 올려주세요. 시간이 조금 촉박합니다..!

**Comment by IDstorage** [comment]
https://www.youtube.com/watch?v=V0byaiK1lXE

유튜브를 통해 한 번 찾아봤습니다!

물론 영상의 내용은 교육에서 제작해볼 조이스틱의 형태는 아니지만 아두이노로 만든 RC카와 컨트롤러(영상 속에서는 스마트폰) 사이의 통신에 대한 내용이 담겨 있고 이를 가르치는 장면이 잘 내포되어 있다 생각하여 선택하였습니다.
